n = input('Digite algo ')
print('O tipo primitivo desse valor é ',type(n))
print('só tem espaços? ',n.isspace())
print('é um numero?', n.isnumeric())
print('é alfabético?',n.isalpha())
print('é alfanumérico?',n.isalnum())
print('esta em maiusculas?',n.isupper())
print('esta em minusculas?',n.islower())
print('esta capitalizada?',n.istitle())
print(n.isascii())
print(n.isdecimal())
print(n.isdigit())
print(n.isdecimal())
print(n.isidentifier())
